apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: postgres-cluster
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30032  # 30000-32767 arası olmalı