apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: milvus-grpc
  namespace: milvus
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`milvus.local`)
      kind: Rule
      services:
        - name: my-milvus
          port: 19530